// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostalService.DAL.Models;

namespace PostalService.DAL.Migrations
{
    [DbContext(typeof(PostalDbContext))]
    [Migration("20220217184508_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PostalService.DAL.Models.PackageModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityOfDeparture")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DateOfDeparture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReceived")
                        .HasColumnType("bit");

                    b.Property<string>("Sender")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            CityOfDeparture = "Coloma, Colorado",
                            DateOfDeparture = "02-01-2021",
                            IsReceived = true,
                            Sender = "Ramsey Fuller",
                            UserId = 1,
                            Weight = 100
                        },
                        new
                        {
                            Id = 1,
                            CityOfDeparture = "Blanford, Georgia",
                            DateOfDeparture = "05-07-2019",
                            IsReceived = false,
                            Sender = "Bailey Dunn",
                            UserId = 16,
                            Weight = 26
                        },
                        new
                        {
                            Id = 2,
                            CityOfDeparture = "Corinne, Connecticut",
                            DateOfDeparture = "14-06-2019",
                            IsReceived = true,
                            Sender = "Russo Howe",
                            UserId = 13,
                            Weight = 15
                        },
                        new
                        {
                            Id = 3,
                            CityOfDeparture = "Balm, Idaho",
                            DateOfDeparture = "14-07-2014",
                            IsReceived = false,
                            Sender = "Stuart Powell",
                            UserId = 16,
                            Weight = 76
                        },
                        new
                        {
                            Id = 4,
                            CityOfDeparture = "Hegins, Texas",
                            DateOfDeparture = "18-12-2016",
                            IsReceived = false,
                            Sender = "Oneill Fitzpatrick",
                            UserId = 12,
                            Weight = 91
                        },
                        new
                        {
                            Id = 5,
                            CityOfDeparture = "Tilden, Mississippi",
                            DateOfDeparture = "05-09-2014",
                            IsReceived = true,
                            Sender = "Haney Patterson",
                            UserId = 18,
                            Weight = 4
                        },
                        new
                        {
                            Id = 6,
                            CityOfDeparture = "Edinburg, Palau",
                            DateOfDeparture = "13-12-2016",
                            IsReceived = false,
                            Sender = "Valarie Aguilar",
                            UserId = 14,
                            Weight = 85
                        },
                        new
                        {
                            Id = 7,
                            CityOfDeparture = "Ironton, Marshall Islands",
                            DateOfDeparture = "29-07-2016",
                            IsReceived = true,
                            Sender = "Staci Black",
                            UserId = 1,
                            Weight = 34
                        },
                        new
                        {
                            Id = 8,
                            CityOfDeparture = "Waikele, California",
                            DateOfDeparture = "09-10-2015",
                            IsReceived = true,
                            Sender = "Berta Watkins",
                            UserId = 6,
                            Weight = 88
                        },
                        new
                        {
                            Id = 9,
                            CityOfDeparture = "Southview, Pennsylvania",
                            DateOfDeparture = "27-11-2015",
                            IsReceived = true,
                            Sender = "Wells Nielsen",
                            UserId = 10,
                            Weight = 92
                        },
                        new
                        {
                            Id = 10,
                            CityOfDeparture = "Gordon, Guam",
                            DateOfDeparture = "06-11-2018",
                            IsReceived = true,
                            Sender = "Laurie Heath",
                            UserId = 6,
                            Weight = 39
                        },
                        new
                        {
                            Id = 11,
                            CityOfDeparture = "Sunriver, Utah",
                            DateOfDeparture = "06-07-2017",
                            IsReceived = true,
                            Sender = "Maxine Hardy",
                            UserId = 10,
                            Weight = 71
                        },
                        new
                        {
                            Id = 12,
                            CityOfDeparture = "Southmont, Montana",
                            DateOfDeparture = "17-12-2016",
                            IsReceived = false,
                            Sender = "Kristy Berry",
                            UserId = 10,
                            Weight = 88
                        },
                        new
                        {
                            Id = 13,
                            CityOfDeparture = "Lopezo, South Carolina",
                            DateOfDeparture = "17-12-2019",
                            IsReceived = false,
                            Sender = "Kirsten Bradford",
                            UserId = 6,
                            Weight = 86
                        },
                        new
                        {
                            Id = 14,
                            CityOfDeparture = "Riegelwood, Kansas",
                            DateOfDeparture = "30-05-2014",
                            IsReceived = false,
                            Sender = "Marlene Foster",
                            UserId = 14,
                            Weight = 91
                        },
                        new
                        {
                            Id = 15,
                            CityOfDeparture = "Dunlo, District Of Columbia",
                            DateOfDeparture = "16-11-2019",
                            IsReceived = true,
                            Sender = "Garrison Best",
                            UserId = 18,
                            Weight = 52
                        },
                        new
                        {
                            Id = 16,
                            CityOfDeparture = "Freeburn, New Mexico",
                            DateOfDeparture = "10-12-2017",
                            IsReceived = false,
                            Sender = "Rena Wheeler",
                            UserId = 6,
                            Weight = 20
                        },
                        new
                        {
                            Id = 17,
                            CityOfDeparture = "Rivera, American Samoa",
                            DateOfDeparture = "29-02-2020",
                            IsReceived = true,
                            Sender = "Nina Carver",
                            UserId = 16,
                            Weight = 63
                        },
                        new
                        {
                            Id = 18,
                            CityOfDeparture = "Eggertsville, Wisconsin",
                            DateOfDeparture = "19-06-2014",
                            IsReceived = true,
                            Sender = "Anderson Kirk",
                            UserId = 4,
                            Weight = 25
                        },
                        new
                        {
                            Id = 19,
                            CityOfDeparture = "Baker, Alaska",
                            DateOfDeparture = "18-01-2018",
                            IsReceived = true,
                            Sender = "Tonya Aguirre",
                            UserId = 16,
                            Weight = 70
                        },
                        new
                        {
                            Id = 20,
                            CityOfDeparture = "Celeryville, Michigan",
                            DateOfDeparture = "17-03-2015",
                            IsReceived = false,
                            Sender = "Myers Gentry",
                            UserId = 12,
                            Weight = 43
                        },
                        new
                        {
                            Id = 21,
                            CityOfDeparture = "Chicopee, New Hampshire",
                            DateOfDeparture = "28-05-2015",
                            IsReceived = false,
                            Sender = "Melba Mcmahon",
                            UserId = 9,
                            Weight = 84
                        },
                        new
                        {
                            Id = 22,
                            CityOfDeparture = "Wildwood, Hawaii",
                            DateOfDeparture = "24-03-2015",
                            IsReceived = true,
                            Sender = "Evans Parsons",
                            UserId = 18,
                            Weight = 22
                        },
                        new
                        {
                            Id = 23,
                            CityOfDeparture = "Kimmell, Oklahoma",
                            DateOfDeparture = "09-05-2019",
                            IsReceived = false,
                            Sender = "Abby Sawyer",
                            UserId = 14,
                            Weight = 24
                        },
                        new
                        {
                            Id = 24,
                            CityOfDeparture = "Brooktrails, Arkansas",
                            DateOfDeparture = "14-05-2021",
                            IsReceived = true,
                            Sender = "Compton Beasley",
                            UserId = 10,
                            Weight = 60
                        },
                        new
                        {
                            Id = 25,
                            CityOfDeparture = "Advance, North Carolina",
                            DateOfDeparture = "05-06-2019",
                            IsReceived = true,
                            Sender = "Marcia Herrera",
                            UserId = 3,
                            Weight = 23
                        },
                        new
                        {
                            Id = 26,
                            CityOfDeparture = "Welda, Massachusetts",
                            DateOfDeparture = "29-08-2017",
                            IsReceived = false,
                            Sender = "Jodi Barrera",
                            UserId = 6,
                            Weight = 60
                        },
                        new
                        {
                            Id = 27,
                            CityOfDeparture = "Blairstown, Maryland",
                            DateOfDeparture = "19-12-2020",
                            IsReceived = false,
                            Sender = "Wendy Curtis",
                            UserId = 0,
                            Weight = 33
                        },
                        new
                        {
                            Id = 28,
                            CityOfDeparture = "Day, Rhode Island",
                            DateOfDeparture = "11-01-2020",
                            IsReceived = false,
                            Sender = "Chris Moran",
                            UserId = 17,
                            Weight = 31
                        },
                        new
                        {
                            Id = 29,
                            CityOfDeparture = "Heil, Kentucky",
                            DateOfDeparture = "17-09-2020",
                            IsReceived = true,
                            Sender = "Sophia Mcmillan",
                            UserId = 5,
                            Weight = 1
                        },
                        new
                        {
                            Id = 30,
                            CityOfDeparture = "Norvelt, West Virginia",
                            DateOfDeparture = "23-09-2017",
                            IsReceived = false,
                            Sender = "Floyd Meyer",
                            UserId = 9,
                            Weight = 53
                        },
                        new
                        {
                            Id = 31,
                            CityOfDeparture = "Madrid, Virginia",
                            DateOfDeparture = "26-06-2015",
                            IsReceived = true,
                            Sender = "Weaver Long",
                            UserId = 15,
                            Weight = 14
                        },
                        new
                        {
                            Id = 32,
                            CityOfDeparture = "Gerton, Tennessee",
                            DateOfDeparture = "21-06-2019",
                            IsReceived = true,
                            Sender = "Lorie Jimenez",
                            UserId = 0,
                            Weight = 1
                        },
                        new
                        {
                            Id = 33,
                            CityOfDeparture = "Ferney, Nevada",
                            DateOfDeparture = "24-02-2015",
                            IsReceived = true,
                            Sender = "Murray Stuart",
                            UserId = 13,
                            Weight = 8
                        },
                        new
                        {
                            Id = 34,
                            CityOfDeparture = "Nogal, Ohio",
                            DateOfDeparture = "26-10-2021",
                            IsReceived = true,
                            Sender = "Morton Dickerson",
                            UserId = 13,
                            Weight = 28
                        },
                        new
                        {
                            Id = 35,
                            CityOfDeparture = "Brandermill, Illinois",
                            DateOfDeparture = "08-09-2020",
                            IsReceived = true,
                            Sender = "Justine Byrd",
                            UserId = 1,
                            Weight = 81
                        },
                        new
                        {
                            Id = 36,
                            CityOfDeparture = "Callaghan, Indiana",
                            DateOfDeparture = "20-06-2021",
                            IsReceived = true,
                            Sender = "Jeanne Wilkins",
                            UserId = 8,
                            Weight = 28
                        },
                        new
                        {
                            Id = 37,
                            CityOfDeparture = "Lutsen, North Dakota",
                            DateOfDeparture = "05-02-2015",
                            IsReceived = true,
                            Sender = "Mills Gonzalez",
                            UserId = 17,
                            Weight = 83
                        },
                        new
                        {
                            Id = 38,
                            CityOfDeparture = "Warren, Washington",
                            DateOfDeparture = "23-09-2019",
                            IsReceived = true,
                            Sender = "Chaney Obrien",
                            UserId = 12,
                            Weight = 76
                        },
                        new
                        {
                            Id = 39,
                            CityOfDeparture = "Rosedale, Florida",
                            DateOfDeparture = "01-01-2022",
                            IsReceived = false,
                            Sender = "Knapp Odom",
                            UserId = 7,
                            Weight = 97
                        },
                        new
                        {
                            Id = 40,
                            CityOfDeparture = "Dante, Arizona",
                            DateOfDeparture = "23-03-2021",
                            IsReceived = false,
                            Sender = "Yesenia Gay",
                            UserId = 10,
                            Weight = 39
                        },
                        new
                        {
                            Id = 41,
                            CityOfDeparture = "Gila, Northern Mariana Islands",
                            DateOfDeparture = "23-04-2016",
                            IsReceived = false,
                            Sender = "Laura Branch",
                            UserId = 4,
                            Weight = 42
                        },
                        new
                        {
                            Id = 42,
                            CityOfDeparture = "Oley, Wyoming",
                            DateOfDeparture = "07-04-2015",
                            IsReceived = false,
                            Sender = "Dean Burt",
                            UserId = 19,
                            Weight = 40
                        },
                        new
                        {
                            Id = 43,
                            CityOfDeparture = "Gloucester, Delaware",
                            DateOfDeparture = "23-10-2018",
                            IsReceived = true,
                            Sender = "Everett Reid",
                            UserId = 7,
                            Weight = 38
                        },
                        new
                        {
                            Id = 44,
                            CityOfDeparture = "Evergreen, Louisiana",
                            DateOfDeparture = "13-05-2016",
                            IsReceived = false,
                            Sender = "Blanca Mills",
                            UserId = 18,
                            Weight = 23
                        });
                });

            modelBuilder.Entity("PostalService.DAL.Models.UserModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Address = "909 Box Street, Worton, Indiana, 637",
                            Age = 33,
                            Email = "richmondmccarty@accufarm.com",
                            Gender = "male",
                            Name = "Richmond Mccarty",
                            Phone = "+1 (894) 437-2065"
                        },
                        new
                        {
                            Id = 1,
                            Address = "187 Hull Street, Hannasville, Wisconsin, 3600",
                            Age = 25,
                            Email = "savannahjordan@accufarm.com",
                            Gender = "female",
                            Name = "Savannah Jordan",
                            Phone = "+1 (803) 424-2419"
                        },
                        new
                        {
                            Id = 2,
                            Address = "714 Church Lane, Cloverdale, North Carolina, 545",
                            Age = 21,
                            Email = "tammibarber@accufarm.com",
                            Gender = "female",
                            Name = "Tammi Barber",
                            Phone = "+1 (851) 522-2432"
                        },
                        new
                        {
                            Id = 3,
                            Address = "617 Paerdegat Avenue, Sanford, Palau, 2782",
                            Age = 39,
                            Email = "dunlapblanchard@accufarm.com",
                            Gender = "male",
                            Name = "Dunlap Blanchard",
                            Phone = "+1 (995) 442-3546"
                        },
                        new
                        {
                            Id = 4,
                            Address = "271 Delmonico Place, Garnet, Connecticut, 862",
                            Age = 39,
                            Email = "bertiemccullough@accufarm.com",
                            Gender = "female",
                            Name = "Bertie Mccullough",
                            Phone = "+1 (834) 546-2323"
                        },
                        new
                        {
                            Id = 5,
                            Address = "438 Manor Court, Wauhillau, Virginia, 4427",
                            Age = 31,
                            Email = "florencehoover@accufarm.com",
                            Gender = "female",
                            Name = "Florence Hoover",
                            Phone = "+1 (921) 493-3196"
                        },
                        new
                        {
                            Id = 6,
                            Address = "791 Oakland Place, Franklin, Louisiana, 5163",
                            Age = 37,
                            Email = "lynettemartinez@accufarm.com",
                            Gender = "female",
                            Name = "Lynette Martinez",
                            Phone = "+1 (954) 486-3738"
                        },
                        new
                        {
                            Id = 7,
                            Address = "564 Balfour Place, Gorham, Maine, 4205",
                            Age = 25,
                            Email = "newtonhaley@accufarm.com",
                            Gender = "male",
                            Name = "Newton Haley",
                            Phone = "+1 (938) 495-3273"
                        },
                        new
                        {
                            Id = 8,
                            Address = "892 Jefferson Street, Sutton, Florida, 7400",
                            Age = 33,
                            Email = "kristinsims@accufarm.com",
                            Gender = "female",
                            Name = "Kristin Sims",
                            Phone = "+1 (841) 587-2856"
                        },
                        new
                        {
                            Id = 9,
                            Address = "455 Calyer Street, Hegins, Michigan, 8471",
                            Age = 30,
                            Email = "adelapennington@accufarm.com",
                            Gender = "female",
                            Name = "Adela Pennington",
                            Phone = "+1 (901) 474-2632"
                        },
                        new
                        {
                            Id = 10,
                            Address = "617 Maujer Street, Camas, Northern Mariana Islands, 8294",
                            Age = 21,
                            Email = "glasspuckett@accufarm.com",
                            Gender = "male",
                            Name = "Glass Puckett",
                            Phone = "+1 (887) 549-3708"
                        },
                        new
                        {
                            Id = 11,
                            Address = "758 Amboy Street, Glendale, Texas, 1933",
                            Age = 31,
                            Email = "louisaclayton@accufarm.com",
                            Gender = "female",
                            Name = "Louisa Clayton",
                            Phone = "+1 (826) 483-3284"
                        },
                        new
                        {
                            Id = 12,
                            Address = "323 Chester Street, Dola, South Carolina, 1712",
                            Age = 31,
                            Email = "gentrybaxter@accufarm.com",
                            Gender = "male",
                            Name = "Gentry Baxter",
                            Phone = "+1 (818) 425-2850"
                        },
                        new
                        {
                            Id = 13,
                            Address = "706 Pineapple Street, Beaulieu, New Jersey, 3592",
                            Age = 27,
                            Email = "kellycharles@accufarm.com",
                            Gender = "female",
                            Name = "Kelly Charles",
                            Phone = "+1 (947) 514-2550"
                        },
                        new
                        {
                            Id = 14,
                            Address = "416 Bush Street, Kempton, Federated States Of Micronesia, 5660",
                            Age = 29,
                            Email = "calliebryan@accufarm.com",
                            Gender = "female",
                            Name = "Callie Bryan",
                            Phone = "+1 (992) 503-3878"
                        },
                        new
                        {
                            Id = 15,
                            Address = "237 Hubbard Place, Mappsville, Pennsylvania, 5516",
                            Age = 23,
                            Email = "tamerabrown@accufarm.com",
                            Gender = "female",
                            Name = "Tamera Brown",
                            Phone = "+1 (958) 413-3631"
                        },
                        new
                        {
                            Id = 16,
                            Address = "705 Arion Place, Spokane, West Virginia, 9127",
                            Age = 25,
                            Email = "maddenmunoz@accufarm.com",
                            Gender = "male",
                            Name = "Madden Munoz",
                            Phone = "+1 (994) 469-3467"
                        },
                        new
                        {
                            Id = 17,
                            Address = "356 Vine Street, Lorraine, Arizona, 2095",
                            Age = 20,
                            Email = "lavernerichards@accufarm.com",
                            Gender = "female",
                            Name = "Laverne Richards",
                            Phone = "+1 (844) 424-3526"
                        },
                        new
                        {
                            Id = 18,
                            Address = "649 Bedell Lane, Kula, Marshall Islands, 4887",
                            Age = 25,
                            Email = "esperanzagarrett@accufarm.com",
                            Gender = "female",
                            Name = "Esperanza Garrett",
                            Phone = "+1 (969) 477-2466"
                        },
                        new
                        {
                            Id = 19,
                            Address = "669 Holt Court, Riner, Wyoming, 8151",
                            Age = 28,
                            Email = "robinsonhowe@accufarm.com",
                            Gender = "male",
                            Name = "Robinson Howe",
                            Phone = "+1 (979) 491-3145"
                        });
                });

            modelBuilder.Entity("PostalService.DAL.Models.PackageModel", b =>
                {
                    b.HasOne("PostalService.DAL.Models.UserModel", "User")
                        .WithMany("Packages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PostalService.DAL.Models.UserModel", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
